services:
  api:
    build:
      # context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - postgres.env