name: Linter
on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing modules
      run: yarn

    - name: Running linter
      run: yarn lint